<?xml version="1.0"?>
<package format="2">
  <name>lidar_undistortion_ros</name>
  <version>0.0.0</version>
  <description>The lidar_undistortion_ros package</description>

  <maintainer email="yifu@robots.ox.ac.uk">Ethan Yifu Tao</maintainer>
  <maintainer email="mfallon@robots.ox.ac.uk">Maurice Fallon</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>lidar_undistortion</depend>
  <depend>lidar_undistortion_msgs</depend>
  <depend>image_transport</depend>
  <depend>cv_bridge</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_eigen</depend>
  <depend>pcl_conversions</depend>
  <depend>velodyne_msgs</depend>
  <!-- The export tag contains other, unspecified, tags -->

<buildtool_depend>rosidl_default_generators</buildtool_depend>
<exec_depend>rosidl_default_runtime</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
