<?xml version="1.0"?>
<package format="3">
  <name>lidar_undistortion</name>
  <version>1.0.0</version>
  <description>Undistort pointclouds using an odometry input</description>

  <maintainer email="yifu@robots.ox.ac.uk">Ethan Yifu Tao</maintainer>
  <maintainer email="mfallon@robots.ox.ac.uk">Maurice Fallon</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
  <test_depend>ament_cmake_gtest</test_depend>
</package>
