<?xml version="1.0"?>
<package format="2">
  <name>lidar_undistortion</name>
  <version>1.0.0</version>
  <description>Undistort pointclouds using an odometry input</description>

  <maintainer email="mcamurri@robots.ox.ac.uk">Marco Camurri</maintainer>
  
  <author email="victorr@ethz.ch">Victor Reijgwart</author>
  <author email="mcamurri@robots.ox.ac.uk">Marco Camurri</author>

  <license>ASL 2.0</license>

  <buildtool_depend>catkin</buildtool_depend>

  <test_depend>rosunit</test_depend>
</package>
