<?xml version="1.0"?>
<package format="3">
  <name>lidar_undistortion</name>
  <version>1.0.0</version>
  <description>Undistort pointclouds using an odometry input</description>

  <maintainer email="mcamurri@robots.ox.ac.uk">Marco Camurri</maintainer>
  
  <author email="victorr@ethz.ch">Victor Reijgwart</author>
  <author email="mcamurri@robots.ox.ac.uk">Marco Camurri</author>

  <license>ASL 2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
  <test_depend>ament_cmake_gtest</test_depend>
</package>
