#ifndef LIDAR_UNDISTORTION_LIDAR_UNDISTORTER_H_
#define LIDAR_UNDISTORTION_LIDAR_UNDISTORTER_H_

#include <Eigen/Eigen>
#include <string>
#include <pcl/point_cloud.h>
#include <pcl/common/transforms.h>
#include "lidar_undistortion/pose_buffer.hpp"
#include "lidar_undistortion/print_macros.hpp"

namespace lidar_undistortion {

template<class PointT>
class LidarUndistorter {
public:
  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
public:
  using PointCloud = typename pcl::PointCloud<PointT>;
  using PointCloudPtr = typename PointCloud::Ptr;
  using CloudHistory = std::map<uint64_t, PointCloudPtr>;
  using PosePair = std::pair<uint64_t, Eigen::Isometry3d>;
  using Vector3d = PoseBuffer::Vector3d;
  using Quaternion = PoseBuffer::Quaternion;

  LidarUndistorter() : times_lut_(beams_, 0) {

  }

  LidarUndistorter(uint64_t pose_buffer_length) : odometry_history_(pose_buffer_length),
  times_lut_(beams_, 0){

  }

  virtual ~LidarUndistorter() {

  }

  virtual void addPose(uint64_t nsec, Eigen::Isometry3d& pose);

  /**
   * @brief processCloud attepts to dewarp a point cloud generated by a moving
   * LiDAR by using the history of poses collected previously to compensate for
   * the motion of the sensor during a sweep operation (~100 ms)
   * @param[in,out] pointcloud a \c const reference to a
   * boost::shared_ptr<OusterCloud> object pointing to the distorted pointcloud.
   * @note if the function succeeds, the data pointed by \p pointcloud
   * <b>are overwritten</b>. The \c const is applied to the pointer,
   * not the data it points to! In case of failure (because of missing
   * transforms in the buffer), the ownership of \p pointcloud is shared
   * internally within a buffer of clouds for future processing.
   * @param[in] timestamp starting time of the scan, in nanoseconds from the
   * Epoch
   * @return \c true if the cloud is successfully dewarped, \c false otherwise.
   */
  virtual bool processCloud(const typename PointCloud::Ptr& pointcloud,
                            const uint64_t timestamp);


protected:
  Eigen::Isometry3d base_to_lidar_ = Eigen::Isometry3d::Identity();
  CloudHistory cloud_history_;
  PoseBuffer odometry_history_;
  uint8_t rings_ = 64; // number of rings per full scan
  uint16_t beams_ = 1024; // number of beams per each ring
  // container that returns the time offset from the start of the scan given
  // the beam number
  std::vector<uint32_t> times_lut_;
};


template <class PointT>
inline bool LidarUndistorter<PointT>::processCloud(const typename PointCloud::Ptr &pointcloud,
                                      const uint64_t timestamp) {
  // Assert that the pointcloud is not empty
  if (pointcloud->empty()){
    return false;
  }
  // Get the start and end times of the pointcloud
  // t_start should be the same as timestamp
  uint64_t t_start = timestamp + times_lut_.front();
  uint64_t t_end = timestamp + times_lut_.back();

  Eigen::Isometry3d T_S_F_original = Eigen::Isometry3d::Identity();
  Eigen::Isometry3d T_S_F_end = Eigen::Isometry3d::Identity();

  // Get the frame that the cloud should be expressed in
  if(!odometry_history_.getInterpolatedPose(t_start, T_S_F_original))

  {
    DEBUG_PRINTLN("Couldn't get interpolated start pose for time " << t_start - time_offset
                    << "\n Starting time     : " << (odometry_history_.empty() ? std::string("none") : std::to_string(odometry_history_.startTime() - time_offset))
                    << "\n End time          : " << (odometry_history_.empty() ? std::string("none") : std::to_string(odometry_history_.endTime() - time_offset))
                    << "\n Pose history size : " << odometry_history_.size()
                    << "\n Cloud history size: " << cloud_history_.size());

    // if the cloud is not in the cloud buffer, we add it
    if(cloud_history_.find(timestamp) == cloud_history_.end()){
      cloud_history_[timestamp] = pointcloud;
      std::cerr << "point cloud shared after collection: " << pointcloud.use_count() << std::endl;
      DEBUG_PRINTLN("Adding cloud to cloud history."
                << "\n Cloud history size: " << cloud_history_.size());
    }
    return false;
  } else {
    // add the just computed interpolated pose to the buffer of poses
    // in case we need it later
    odometry_history_.addPose(timestamp, T_S_F_original);
    DEBUG_PRINTLN("Adding interpolated pose to pose history"
                  << "\n Pose history size: " << odometry_history_.size());
  }

  // Check if the end pose is available and abort if not available
  if(!odometry_history_.getInterpolatedPose(t_end, T_S_F_end)){
    DEBUG_PRINTLN("Couldn't get interpolated end pose for time " << t_end - time_offset
                    << "\n Starting time     : " << (odometry_history_.empty() ? std::string("none") : std::to_string(odometry_history_.startTime()- time_offset))
                    << "\n End time          : " << (odometry_history_.empty() ? std::string("none") : std::to_string(odometry_history_.endTime() - time_offset))
                    << "\n Pose history size : " << odometry_history_.size()
                    << "\n Cloud history size: " << cloud_history_.size());

    // if the cloud is not in the cloud buffer, we add it
    if(cloud_history_.find(timestamp) == cloud_history_.end()){
      cloud_history_[timestamp] = pointcloud;
      std::cerr << "point cloud shared after collection: " << pointcloud.use_count() << std::endl;

      DEBUG_PRINTLN("Adding cloud to cloud history."
                      << "\n Cloud history size: " << cloud_history_.size());
    }
    return false;
  } else {
    // add the just computed interpolated pose to the buffer of poses
    // in case we need it later
    odometry_history_.addPose(t_end, T_S_F_end);
    DEBUG_PRINTLN("Adding interpolated pose to pose history"
                    << "\n Pose history size: " << odometry_history_.size());
  }

  // Compute the transform used to project the corrected pointcloud back into
  // lidar's scan frame, for more info see the current class' header

  // Correct the distortion on all points, using the LiDAR's true pose at
  // each point's timestamp
  uint32_t last_transform_update_t = 0;

  Eigen::Isometry3d T_S_original__S_corrected = Eigen::Isometry3d::Identity();
  size_t point_counter = 0;
  for (auto &point : pointcloud->points) {
    // Check if the current point's timestamp differs from the previous one
    // If so, lookup the new corresponding transform
    if (times_lut_[point_counter] != last_transform_update_t) {
      last_transform_update_t = times_lut_[point_counter];
      uint64_t point_t = timestamp + times_lut_[point_counter];

      Eigen::Isometry3d T_F_S_correct;
      if(!odometry_history_.getInterpolatedPose(point_t, T_F_S_correct)){
        DEBUG_PRINTLN("Couldn't get interpolated point pose for time " << point_t- time_offset
                        << "\n Starting time: " << (odometry_history_.empty() ? std::string("none") : std::to_string(odometry_history_.startTime() - time_offset))
                        << "\n End time     : " << (odometry_history_.empty() ? std::string("none") : std::to_string(odometry_history_.endTime() - time_offset)));
        // if the cloud is not in the cloud buffer, we add it
        if(cloud_history_.find(timestamp) == cloud_history_.end()){
          cloud_history_[timestamp] = pointcloud;
          DEBUG_PRINTLN("Adding cloud to cloud history."
                          << "\n Cloud history size: " << cloud_history_.size());
        }
        return false;
      } else {
        // add the just computed interpolated pose to the buffer of poses
        // in case we need it later
        odometry_history_.addPose(point_t, T_F_S_correct);
        DEBUG_PRINTLN("Adding interpolated pose to pose history"
                        << "\n Pose history size: " << odometry_history_.size());
      }
      T_S_original__S_corrected = T_S_F_original.inverse() * T_F_S_correct;
    }

    // Correct the point's distortion, by transforming it into the fixed
    // frame based on the LiDAR sensor's current true pose, and then transform
    // it back into the lidar scan frame
    point = pcl::transformPoint(point, T_S_original__S_corrected.cast<float>());
    point_counter++;
  }

  return true;
}


template <class PointT>
inline void LidarUndistorter<PointT>::addPose(uint64_t nsec, Eigen::Isometry3d &pose)
{
  //@todo use move constructor for speedup
  odometry_history_.addPose(nsec, pose * base_to_lidar_);
  DEBUG_PRINTLN("Pose history size: " << odometry_history_.size());

  // if there are point clouds in the buffer, we process them
  if(!cloud_history_.empty() && !odometry_history_.empty()){
    for(auto it = cloud_history_.lower_bound(odometry_history_.startTime()); it != cloud_history_.end(); ){
      DEBUG_PRINTLN("Processing cloud " << it->first - time_offset);
      if(!processCloud(it->second, it->first)){
        ++it;
      } else {
        DEBUG_PRINTLN("Processed. Cloud size is: " << cloud_history_.size());
        // the point cloud has been transformed successfully
        // we remove it from the buffer and return
        it = cloud_history_.erase(it);
      }
    }
  }
}

}  // namespace lidar_undistortion

#endif  // LIDAR_UNDISTORTION_LIDAR_UNDISTORTER_H_
