#ifndef LIDAR_UNDISTORTION_LIDAR_UNDISTORTER_H_
#define LIDAR_UNDISTORTION_LIDAR_UNDISTORTER_H_

#include <Eigen/Geometry>
#include <string>
#include <pcl/point_cloud.h>
#include "lidar_undistortion/pose_buffer.hpp"
#include "lidar_undistortion/print_macros.hpp"
#include <algorithm>

namespace lidar_undistortion {

template<class PointT>
class LidarUndistorter {
public:
  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
public:
  using PointCloud = typename pcl::PointCloud<PointT>;
  using PointCloudPtr = typename PointCloud::Ptr;
  using CloudHistory = std::map<uint64_t, PointCloudPtr>;
  using PosePair = std::pair<uint64_t, Eigen::Isometry3d>;
  using Vector3d = PoseBuffer::Vector3d;
  using Quaternion = PoseBuffer::Quaternion;


  LidarUndistorter(uint64_t pose_buffer_length) : odometry_history_(pose_buffer_length),
  times_lut_(beams_*rings_, 0) {


  }

  LidarUndistorter() : LidarUndistorter(1e9) {
  }


  virtual ~LidarUndistorter() = default;

  virtual void addPose(uint64_t nsec, const Eigen::Isometry3d &pose);

  /**
   * @brief processCloud attepts to dewarp a point cloud generated by a moving
   * LiDAR by using the history of poses collected previously to compensate for
   * the motion of the sensor during a sweep operation (~100 ms)
   * @param[in,out] pointcloud a \c const reference to a
   * boost::shared_ptr<OusterCloud> object pointing to the distorted pointcloud.
   * @note if the function succeeds, the data pointed by \p pointcloud
   * <b>are overwritten</b>. The \c const is applied to the pointer,
   * not the data it points to! In case of failure (because of missing
   * transforms in the buffer), the ownership of \p pointcloud is shared
   * internally within a buffer of clouds for future processing.
   * @param[in] start_timestamp absolute starting time of the scan,
   * in nanoseconds from the Epoch
   * @param[in] desired_timestamp absolute time (from the Epoch) at which we
   * we want to express the point cloud. This time has to be between the start
   * and the end of the scan (this is not checked at the moment though
   * @return \c true if the cloud is successfully dewarped, \c false otherwise.
   * @sa processCloud(const typename PointCloud::Ptr& pointcloud,
                            const uint64_t start_timestamp)
   */
  virtual bool processCloud(const typename PointCloud::Ptr& pointcloud,
                            const uint64_t start_timestamp,
                            const uint64_t desired_timestamp);

  /**
   * @brief processCloud overload of processCloud(const typename PointCloud::Ptr& pointcloud,
                            const uint64_t start_timestamp,
                            const uint64_t desired_timestamp) where the desired
                            timestamp coincides with the start timestamp
   * @param pointcloud
   * @param start_timestamp
   * @return
   */
  virtual bool processCloud(const typename PointCloud::Ptr& pointcloud,
                            const uint64_t start_timestamp) {
    return processCloud(pointcloud, start_timestamp, start_timestamp);
  }

  virtual void reprocessCloudBuffer();

  /**
   * @brief setRingsAndBeams sets the number of rings and of beams of the
   * LIDAR device. This changes the internal size of the timings' LUT
   * @param rings
   * @param beams
   */
  void setRingsAndBeams(uint8_t rings, uint16_t beams){
    rings_ = rings;
    beams_ = beams;
    if(times_lut_.size() != rings_*beams_){
      times_lut_.resize(rings_*beams_);
    }
  }

  void setReprocessClouds(const bool reprocess_clouds) {
    reprocess_clouds_ = reprocess_clouds;
  }

  bool getReprocessClouds() const { return reprocess_clouds_; }

protected:
  Eigen::Isometry3d base_to_lidar_ = Eigen::Isometry3d::Identity();
  CloudHistory cloud_history_;
  PoseBuffer odometry_history_;
  uint8_t rings_ = 64; // number of rings per full scan
  uint16_t beams_ = 1024; // number of beams per each ring
  // container that returns the time offset from the start of the scan given
  // the beam number
  std::vector<int32_t> times_lut_;

  bool reprocess_clouds_ = true;
};

template <class PointT>
inline bool LidarUndistorter<PointT>::processCloud(const typename PointCloud::Ptr &pointcloud,
                                                   const uint64_t start_timestamp,
                                                   const uint64_t desired_timestamp)
{
  // Assert that the pointcloud is not empty
  if (pointcloud->empty()){
    DEBUG_PRINTLN("Point cloud empty!");
    return false;
  }
  // Get the start and end times of the pointcloud
  // t_start should be the same as timestamp
  const auto minmax_time = std::minmax_element(begin(times_lut_), end(times_lut_));
  DEBUG_PRINTLN("ring_ size is " << unsigned(rings_) << " beam_ size is  "
                                 << beams_ << " time look up table size is "
                                 << times_lut_.size());
  DEBUG_PRINTLN("minmax times : " << (*minmax_time.first ) << " " << (*minmax_time.second));
  const uint64_t t_start = static_cast<uint64_t>(static_cast<int64_t>(start_timestamp) + static_cast<int64_t>(*minmax_time.first));
  const uint64_t t_end =   static_cast<uint64_t>(static_cast<int64_t>(start_timestamp) + static_cast<int64_t>(*minmax_time.second));

  if(start_timestamp != t_start){
    ERROR_PRINTLN("[LidarUndistorter] ERROR: the start timestamp "
                  << "is different than t_start: " << start_timestamp << " != " << t_start);
    return false;
  }

  if(desired_timestamp < t_start || desired_timestamp > t_end){
    ERROR_PRINTLN("[LidarUndistorter] ERROR: the desired timestamp "
                  << "is outside the valid timestamp bounds for the point cloud");
    ERROR_PRINTLN("[LidarUndistorter]"
                  << "\nDesired timestamp: " << desired_timestamp
                  << "\nStart timestamp  : " << t_start
                  << "\nEnd timestamp    : " << t_end);
    return false;
  }

  Eigen::Isometry3d T_S_F_original = Eigen::Isometry3d::Identity();
  Eigen::Isometry3d T_S_F_end = Eigen::Isometry3d::Identity();

  if(!odometry_history_.canInterpolate(t_start)){
    DEBUG_PRINTLN("Can't interpolate time t_start! " << t_start);
    DEBUG_PRINTLN("Odometry history size : " << odometry_history_.size());
    DEBUG_PRINTLN("Odometry history start: " << odometry_history_.startTime());
    DEBUG_PRINTLN("Odometry history end  : " << odometry_history_.endTime());

    if(cloud_history_.find(t_start) == cloud_history_.end()){
      cloud_history_[t_start] = pointcloud;
      DEBUG_PRINTLN("Adding cloud to cloud history."
                << "\n Cloud history size: " << cloud_history_.size());
    }
    return false;
  }

  // Get the frame that the cloud should be expressed in
  if(!odometry_history_.getInterpolatedPose(desired_timestamp, T_S_F_original))
  {
    DEBUG_PRINTLN("Couldn't get interpolated timestamp pose for time " << desired_timestamp
                    << "\n Starting time     : " << (odometry_history_.empty() ? std::string("none") : std::to_string(odometry_history_.startTime()))                    
                    << "\n End time          : " << (odometry_history_.empty() ? std::string("none") : std::to_string(odometry_history_.endTime()))
                    << "\n Pose history size : " << odometry_history_.size()
                    << "\n Cloud history size: " << cloud_history_.size());

    // if the cloud is not in the cloud buffer, we add it
    if(cloud_history_.find(desired_timestamp) == cloud_history_.end()){
      cloud_history_[desired_timestamp] = pointcloud;
      DEBUG_PRINTLN("Adding cloud to cloud history."
                << "\n Cloud history size: " << cloud_history_.size());
    }
    return false;
  } else {
    // add the just computed interpolated pose to the buffer of poses
    // in case we need it later
    odometry_history_.addPose(desired_timestamp, T_S_F_original);
    DEBUG_PRINTLN("Adding interpolated pose to pose history"
                  << "\n Pose history size: " << odometry_history_.size());
  }

  // Check if the end pose is available and abort if not available
  if(!odometry_history_.getInterpolatedPose(t_end, T_S_F_end)){
    DEBUG_PRINTLN("Couldn't get interpolated end pose for time " << t_end
                    << "\n Starting time     : " << (odometry_history_.empty() ? std::string("none") : std::to_string(odometry_history_.startTime() ))
                    << "\n End time          : " << (odometry_history_.empty() ? std::string("none") : std::to_string(odometry_history_.endTime()))
                    << "\n Pose history size : " << odometry_history_.size()
                    << "\n Cloud history size: " << cloud_history_.size());

    // if the cloud is not in the cloud buffer, we add it
    if(cloud_history_.find(desired_timestamp) == cloud_history_.end()){
      cloud_history_[desired_timestamp] = pointcloud;
      DEBUG_PRINTLN("Adding cloud to cloud history."
                      << "\n Cloud history size: " << cloud_history_.size());
    }
    return false;
  } else {
    // add the just computed interpolated pose to the buffer of poses
    // in case we need it later
    odometry_history_.addPose(t_end, T_S_F_end);
    DEBUG_PRINTLN("Adding interpolated pose to pose history"
                    << "\n Pose history size: " << odometry_history_.size());
  }

  // Compute the transform used to project the corrected pointcloud back into
  // lidar's scan frame, for more info see the current class' header

  // Correct the distortion on all points, using the LiDAR's true pose at
  // each point's timestamp
  int32_t last_transform_update_t = 0;
  Eigen::Isometry3d T_F_S_correct = Eigen::Isometry3d::Identity();
  Eigen::Isometry3d T_S_original_S_corrected = Eigen::Isometry3d::Identity();
  const Eigen::Isometry3d T_S_F_original_inverse = T_S_F_original.inverse(); // precompute
  size_t point_counter = 0;

  for (auto &point : pointcloud->points) {
    // Check if the current point's timestamp differs from the previous one
    // If so, lookup the new corresponding transform
    if (times_lut_[point_counter] != last_transform_update_t) {
      last_transform_update_t = times_lut_[point_counter];
      const uint64_t point_t = static_cast<uint64_t>(
          static_cast<int64_t>(start_timestamp) +
          static_cast<int64_t>(times_lut_[point_counter]));

      if(!odometry_history_.getInterpolatedPose(point_t, T_F_S_correct)){
        DEBUG_PRINTLN("Couldn't get interpolated point pose for time " << point_t
                        << "\n Starting time: " << (odometry_history_.empty() ? std::string("none") : std::to_string(odometry_history_.startTime()))
                        << "\n End time     : " << (odometry_history_.empty() ? std::string("none") : std::to_string(odometry_history_.endTime())));
        // if the cloud is not in the cloud buffer, we add it
        if(cloud_history_.find(desired_timestamp) == cloud_history_.end()){
          cloud_history_[desired_timestamp] = pointcloud;
          DEBUG_PRINTLN("Adding cloud to cloud history."
                          << "\n Cloud history size: " << cloud_history_.size());
        }
        return false;
      } else {
        // add the just computed interpolated pose to the buffer of poses
        // in case we need it later
        static constexpr bool SAVE_POSES_FOR_LATER = false;
        if (SAVE_POSES_FOR_LATER) {
          odometry_history_.addPose(point_t, T_F_S_correct);
          DEBUG_PRINTLN("Adding interpolated pose to pose history"
                        << "\n Pose history size: "
                        << odometry_history_.size());
        }
      }
      T_S_original_S_corrected = T_S_F_original_inverse * T_F_S_correct;
    }

    // Correct the point's distortion, by transforming it into the fixed
    // frame based on the LiDAR sensor's current true pose, and then transform
    // it back into the lidar scan frame
    const Eigen::Vector3d pointTransformed =
        T_S_original_S_corrected * Eigen::Vector3d{point.x, point.y, point.z};
    point.x = pointTransformed[0];
    point.y = pointTransformed[1];
    point.z = pointTransformed[2];

    ++point_counter;
  }
  return true;
}


template <class PointT>
inline void LidarUndistorter<PointT>::addPose(uint64_t nsec, const Eigen::Isometry3d &pose)
{
  //@todo use move constructor for speedup
  odometry_history_.addPose(nsec, pose * base_to_lidar_);
  DEBUG_PRINTLN("Pose history size: " << odometry_history_.size());
  reprocessCloudBuffer();
}

template <class PointT>
inline void LidarUndistorter<PointT>::reprocessCloudBuffer(){
  if (!reprocess_clouds_) {
    if (!cloud_history_.empty()) { cloud_history_.clear(); }
    return;
  }

  // if there are point clouds in the buffer, we process them
  if(!cloud_history_.empty() && !odometry_history_.empty()){
    for(auto it = cloud_history_.lower_bound(odometry_history_.startTime()); it != cloud_history_.end(); ){
      DEBUG_PRINTLN("Processing cloud " << it->first);
      if(!processCloud(it->second, it->first)){
        ++it;
      } else {
        DEBUG_PRINTLN("Processed. Cloud size is: " << cloud_history_.size());

        // the point cloud has been transformed successfully
        // we remove it from the buffer and return
        it = cloud_history_.erase(it);
      }
    }
  }
}

}  // namespace lidar_undistortion

#endif  // LIDAR_UNDISTORTION_LIDAR_UNDISTORTER_H_
