<?xml version="1.0"?>
<package format="3">
  <name>lidar_undistortion_msgs</name>
  <version>0.0.0</version>

  <description>
Message from the Lidar Undistortion package
  </description>

  <maintainer email="yifu@robots.ox.ac.uk">Ethan Yifu Tao</maintainer>
  <maintainer email="mfallon@robots.ox.ac.uk">Maurice Fallon</maintainer>
  <license>BSD</license>

  <buildtool_depend>rosidl_default_generators</buildtool_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>
  <member_of_group>rosidl_interface_packages</member_of_group>

  <depend>std_msgs</depend>
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- The export tag contains other, unspecified, tags -->
  <export>
    <!-- Other tools can request additional information be placed here -->
  <build_type>ament_cmake</build_type>
  </export>
</package>
